apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
 name: managed-gitops-cluster
 namespace: openshift-gitops
spec:
 argoServer:
   argoNamespace: openshift-gitops
   cluster: local-cluster
 placementRef:
   kind: Placement
   apiVersion: cluster.open-cluster-management.io/v1beta1   
   name: managed-placement
   namespace: openshift-gitops 